<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
<style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
}
-->
</style></head>
<SCRIPT LANGUAGE="JavaScript"> 
 function log_submit(){ var User = document.mailForm.mail_name.value; var ProNo = document.mailForm.mailSelect.value; var mail_action = ProNo.split(";"); if(mail_action.length > 1) { if(mail_action[1]=="suffix") User += "@"+mail_action[2]; else eval("document.mailForm."+mail_action[1]+".value = '"+mail_action[2]+"';"); } var Passwd = document.mailForm.mail_password.value; var Formobj = document.mailForm; function checkUserPass(){ if (User == ""){ alert("请填写用户名"); document.mailForm.mail_name.focus(); return false; } else if (Passwd == ""){ alert("请填写密码"); document.mailForm.mail_password.focus(); return false; } else { return true; } } if (checkUserPass()){ document.mailForm.action = mail_action[0]; document.mailForm.u.value = User; document.mailForm.user.value = User; document.mailForm.LoginName.value = User; document.mailForm.username.value = User; document.mailForm.UserName.value = User; document.mailForm.login_name.value = User; document.mailForm.login.value = User; document.mailForm.psw.value = Passwd; document.mailForm.pass.value = Passwd; document.mailForm.passwd.value = Passwd; document.mailForm.password.value = Passwd; document.mailForm.Password.value = Passwd; document.mailForm.login_password.value = Passwd; document.mailForm.submit(); document.mailForm.mail_password.value = ""; } return false; } 
</SCRIPT> 

 <table width="180" align="center" cellspacing="0" style="border:1px solid #c0c0c0;font-size:13px">
<tr height=22><form method="post" target="_blank" name="mailForm" onsubmit='return log_submit();'><input type="hidden" name="u" value=""><input type="hidden" name="user" value=""><input type="hidden" name="LoginName" value=""><input type="hidden" name="username" value=""><input type="hidden" name="UserName" value=""><input type="hidden" name="login_name" value=""><input type="hidden" name="login" value=""><input type="hidden" name="psw" value=""><input type="hidden" name="language" value=""><input type="hidden" name="pass" value=""><input type="hidden" name="passwd" value=""><input type="hidden" name="password" value=""><input type="hidden" name="Password" value=""><input type="hidden" name="login_password" value=""><input type="hidden" name="url" value=""><input type="hidden" name="BackURL" value=""><td colspan="2"><select name="mailSelect" size="1"> <option selected>选择你的邮局</option> <option value="http://go.56.com/mail/mail.56">@56.com</option> <option value="http://entry.126.com/cgi/login">@126.com</option> <option value="http://reg.163.com/in.jsp?url=http://fm163.163.com/coremail/fcg/ntesdoor2?username=wd.dm.mailForm.name.value">@163.com</option> <option value="http://mail.sina.com.cn/cgi-bin/login.cgi">@sina.com</option> <option value="http://login.mail.sohu.com/chkpwd.php">@sohu.com</option> <option value="http://bjweb.163.net/cgi/163/login_pro.cgi">@163.net</option> <option value="http://bjweb.mail.tom.com/cgi/163/login_pro.cgi">@Tom.com</option> <option value="http://webmail.21cn.com/NULL/NULL/NULL/NULL/NULL/SignIn.gen">@21cn.com</option> <option value="https://edit.bjs.yahoo.com/config/login">@yahoo.com.cn</option> <option value="http://g2wm.263.net/xmweb">@263.net</option> <option value="http://freemail.eyou.com/cgi-bin/login">@eyou.com</option> <option value="http://webmail.21cn.net/nature/gb/NULL/NULL/NULL/SignIn.gen;DomainName;21cn.net">@21cn.net</option> <option value="http://entry.yeah.net/cgi/login">@Yeah.net</option> <option value="http://vip.163.com/payment/VipLogon.jsp">@vip.163.com</option> <option value="http://vip.sina.com/cgi-bin/login.cgi">@vip.sina.com</option> <option value="http://web.netease.com/cgi/login">@netease.com</option> <option value="http://paymail.china.com/extend/gb/NULL/NULL/NULL/SignIn.gen">@China.com</option> <option value="http://login.chinaren.com/zhs/servlet/Login;url;http:/mail.chinaren.com">@ChinaRen.com</option> <option value="http://mw1.elong.com/cgi-bin/weblogon.cgi">@elong.com</option> <option value="http://login.etang.com/servlet/login;BackURL;http:/mail.etang.com/cgi/door">@etang.com</option> <option value="http://www.zonelove.net/login.asp">@zonelove.net</option> </select> <input type="submit" value="登录" style="background-color:#FFD700"></td><tr><td height=22 colspan=2>&nbsp;用 户 名:<input name="mail_name" onfocus="this.select" size=12></td></tr><tr><td colspan=2>&nbsp;登录密码:<input name="mail_password" onfocus="this.select" type="password" size=12></td></tr></form></table>
<body>

</body>
</html>
